spring.application.name=convenience-store

# ???????
spring.datasource.url=jdbc:mysql://localhost:3306/convenience_store?useSSL=false&serverTimezone=Asia/Tokyo
# MySQL??
spring.datasource.username=root
# MySQL????
spring.datasource.password=
# MySQL??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#? MyBatis ???? resources/mapper ????? XML SQL ?????
mybatis.mapper-locations=classpath*:mapper/*.xml
#?????????????product_name????Java?????
mybatis.configuration.map-underscore-to-camel-case=true